//! Experimental, from-scratch AE26 composition, solid and vector construction.
//!
//! The FX exporter uses the nonempty writer. Adobe acceptance must be verified
//! separately from parsing generated bytes; no source project is loaded here.

mod camera;
mod composition_options;
mod dashes;
mod effect_points;
pub(crate) mod effects;
pub(crate) mod footage;
mod keyframes;
mod layer_options;
mod layer_styles;
mod masks;
mod path_geometry;
pub(crate) use path_geometry::{PathKeyframe, PathTrack, split_path_track, validate_path_track};
mod rects;
mod root;
mod shapes;
mod solids;
pub(crate) mod source_clock;
mod stroke;
pub(crate) mod text;
mod text_document;
mod transform3d;
mod views;

pub(crate) use camera::{NativeCameraSpec, append_if_needed as append_root_camera};
pub(crate) use composition_options::{CompositionOptions, apply as apply_composition_options};
pub(crate) use dashes::StrokeDashes;
pub(crate) use keyframes::{
    Easing as KeyframeEasing, Keyframe as NumericKeyframe, Track as NumericTrack,
};
pub(crate) use layer_options::{NativeLayerOptions, NativeMatteRef};
pub(crate) use masks::{NativeMaskMode, NativeMaskSpec};
#[cfg(test)]
pub(crate) use rects::write_composition;
pub(crate) use rects::{
    LayerReferenceFacts, LayerSpec, LayerTiming, NullLayerSpec, PrecompositionSpec, RectAnimations,
    VectorAppearance, VectorRectSpec, emitted_media_paths, translate_numeric_track,
    validate_layer_payload, validate_layers, write_composition_at_rate,
    write_picture_only_composition_at_rate,
};
pub(crate) use shapes::{
    GeometryAnimations, VectorBooleanSpec, VectorContent, VectorGeometry, VectorGroupAnimations,
    VectorGroupSpec, VectorGroupTransform, VectorLayerSpec, VectorModifierSpec,
    VectorPaintAnimations, VectorPaintSpec, VectorShapeSpec,
};
pub(crate) use solids::TransformAnimations;
pub use solids::{SolidLayerSpec, SolidTransform, write_solid_composition};
pub(crate) use stroke::StrokeAnimations;
pub(crate) use transform3d::{NativeTransform3d, Transform3dAnimations};

use thiserror::Error;

use crate::{rifx::RifxError, schema::RecordError, timing::Duration24};

/// Parameters for the first native writer slice: one empty 24-fps composition.
///
/// Pixel aspect is square, display start is zero, and viewport state is
/// canonicalized. There are no timeline layers or external assets in this API.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CompositionSpec {
    /// Nonempty UTF-8 composition name, without embedded NUL characters.
    pub name: String,
    /// Canvas width in pixels.
    pub width: u16,
    /// Canvas height in pixels.
    pub height: u16,
    /// Positive duration in whole frames at exactly 24 frames per second.
    pub duration_frames: u32,
}

/// A failed native project construction; no bytes have been published.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum AepWriteError {
    /// A selected picture scope was omitted by best-effort conversion.
    #[error("selected AEP scope has no convertible picture")]
    NoConvertiblePicture(Vec<crate::ExportDiagnostic>),
    /// Parameters cannot be represented by this writer slice.
    #[error("invalid After Effects composition: {0}")]
    Invalid(&'static str),
    /// Canonical document identity or source planning is inconsistent.
    #[error("invalid After Effects document: {0}")]
    InvalidDocument(String),
    /// Shared binary schema or RIFX framing rejected the constructed project.
    #[error(transparent)]
    Binary(#[from] RifxError),
    /// A typed fixed-layout record rejected a value.
    #[error(transparent)]
    Record(#[from] RecordError),
}

/// Builds a new native AEP without reading any existing project or invoking AE.
///
/// Only an empty AE26 composition at 24 fps is supported. The bytes are checked
/// by the bounded RIFX serializer; that is not a guarantee of Adobe compatibility.
/// File publication and Tesseract conversion are intentionally separate concerns.
pub fn write_empty_composition(spec: &CompositionSpec) -> Result<Vec<u8>, AepWriteError> {
    let duration = checked_duration(spec)?;
    let view_chunks = views::build_views(spec.width, spec.height, duration)?;
    let project = root::build_project(&spec.name, spec.width, spec.height, duration, view_chunks)?;
    Ok(project.encode()?)
}

pub(crate) fn checked_duration(spec: &CompositionSpec) -> Result<Duration24, AepWriteError> {
    if spec.name.is_empty() || spec.name.contains('\0') {
        return Err(AepWriteError::Invalid("empty name or embedded NUL"));
    }
    // Bound allocation before constructing a UTF-8 chunk, independently of the
    // full-file bound enforced by the RIFX serializer.
    if spec.name.len() > 65_535 {
        return Err(AepWriteError::Invalid("name exceeds 65535 UTF-8 bytes"));
    }
    if spec.width == 0 || spec.height == 0 {
        return Err(AepWriteError::Invalid("zero canvas dimension"));
    }
    if spec.duration_frames == 0 {
        return Err(AepWriteError::Invalid("zero duration"));
    }
    Duration24::from_frames(spec.duration_frames)
        .map_err(|_| AepWriteError::Invalid("duration exceeds the AE signed tick range"))
}

#[cfg(test)]
mod tests {
    use super::{AepWriteError, CompositionSpec, write_empty_composition};
    use crate::{aep::Project, reader::read_empty_composition};

    fn spec() -> CompositionSpec {
        CompositionSpec {
            name: "Rust 検証 Ω".into(),
            width: 640,
            height: 360,
            duration_frames: 72,
        }
    }

    #[test]
    fn generated_projects_preserve_requested_metadata() {
        for (width, height, frames) in [(640, 360, 72), (720, 1280, 48), (1, 1, 1)] {
            let input = CompositionSpec {
                width,
                height,
                duration_frames: frames,
                ..spec()
            };
            let bytes = write_empty_composition(&input).unwrap();
            assert_eq!(Project::parse(&bytes).unwrap().encode().unwrap(), bytes);
            let read = read_empty_composition(&bytes).unwrap();
            assert_eq!(read.name, input.name);
            assert_eq!((read.width, read.height), (width, height));
            assert_eq!(read.duration_secs, f64::from(frames) / 24.0);
            assert_eq!(read.id, 1);
        }
    }

    #[test]
    fn reads_the_generated_projects_after_adobe_resaved_them() {
        // These were first generated by this Rust writer, then opened, checked,
        // and saved by AE26.5. They are regression inputs, never templates.
        for (bytes, name, width, height, seconds) in [
            (
                include_bytes!("../tests/fixtures/ae26_rust_wide_resaved.aep").as_slice(),
                "Rust 検証 Ω",
                640,
                360,
                3.0,
            ),
            (
                include_bytes!("../tests/fixtures/ae26_rust_tall_resaved.aep").as_slice(),
                "RustTall",
                720,
                1280,
                2.0,
            ),
        ] {
            let actual = read_empty_composition(bytes).unwrap();
            assert_eq!(
                (
                    actual.name.as_str(),
                    actual.width,
                    actual.height,
                    actual.duration_secs
                ),
                (name, width, height, seconds)
            );
        }
    }

    #[test]
    fn accepts_largest_signed_view_out_point() {
        let input = CompositionSpec {
            duration_frames: i32::MAX as u32 / 1024,
            ..spec()
        };
        let bytes = write_empty_composition(&input).unwrap();
        assert_eq!(
            read_empty_composition(&bytes).unwrap().duration_secs,
            f64::from(input.duration_frames) / 24.0
        );
    }

    #[test]
    fn fresh_generation_is_deterministic() {
        assert_eq!(
            write_empty_composition(&spec()).unwrap(),
            write_empty_composition(&spec()).unwrap()
        );
    }

    #[test]
    fn rejects_invalid_parameters_before_generation() {
        for input in [
            CompositionSpec { width: 0, ..spec() },
            CompositionSpec {
                height: 0,
                ..spec()
            },
            CompositionSpec {
                name: String::new(),
                ..spec()
            },
            CompositionSpec {
                name: "bad\0name".into(),
                ..spec()
            },
            CompositionSpec {
                name: "x".repeat(65_536),
                ..spec()
            },
            CompositionSpec {
                duration_frames: 0,
                ..spec()
            },
            CompositionSpec {
                duration_frames: u32::MAX,
                ..spec()
            },
            // ldta stores the view out-point as a signed i32 numerator.
            CompositionSpec {
                duration_frames: (i32::MAX as u32 / 1024) + 1,
                ..spec()
            },
        ] {
            assert!(matches!(
                write_empty_composition(&input),
                Err(AepWriteError::Invalid(_))
            ));
        }
    }
}
