//! Native-derived Co-Editor header/GUID/item evidence; no render-fidelity claim.

use serde::Deserialize;

use super::*;
use crate::Limitation;

#[derive(Deserialize)]
struct Provenance {
    fixture: Fixture,
    occurrences: Vec<Occurrence>,
}

#[derive(Deserialize)]
struct Fixture {
    bytes: usize,
    sha256: String,
}

#[derive(Deserialize)]
struct Occurrence {
    occurrence: String,
    importer_prefs: String,
    guid: String,
    item_id: u32,
    item_name: String,
}

#[test]
fn native_format96_guids_select_editable_composition_siblings() {
    let provenance: Provenance = serde_json::from_str(include_str!(
        "../../../../tests/fixtures/hybrid/format96/provenance.json"
    ))
    .unwrap();
    assert_eq!(FORMAT96.len(), provenance.fixture.bytes);
    assert_eq!(
        format!("{:x}", Sha256::digest(FORMAT96)),
        provenance.fixture.sha256
    );
    let root = tempfile::tempdir().unwrap();
    let input = root.path().join("input.aep");
    fs::write(&input, FORMAT96).unwrap();
    let prepared = AfterEffects.prepare_linked_import(&input).unwrap();
    let mut media = LinkedMedia::default();
    let mut next_id = 1000;
    let expected = [
        ("943", 2165),
        ("1131", 41),
        ("1134", 1),
        ("1171", 92),
        ("1276", 121),
    ];
    assert_eq!(provenance.occurrences.len(), expected.len());
    for (occurrence, (native_occurrence, native_item)) in
        provenance.occurrences.iter().zip(expected)
    {
        assert_eq!(occurrence.occurrence, native_occurrence);
        assert_eq!(occurrence.item_id, native_item);
        // These payloads were extracted from Premiere, not generated by our writer.
        let payload = STANDARD.decode(&occurrence.importer_prefs).unwrap();
        assert_eq!(payload.len(), 72);
        let units: Vec<_> = payload
            .chunks_exact(2)
            .map(|pair| u16::from_le_bytes([pair[0], pair[1]]))
            .collect();
        let native_guid = String::from_utf16(&units).unwrap();
        assert_eq!(native_guid, occurrence.guid);
        assert_eq!(&native_guid[8..], "-0000-0000-0000-000000000000");
        let item_id = u32::from_str_radix(&native_guid[..8], 16).unwrap();
        assert_eq!(item_id, native_item);
        let selection = prepared.resolve_composition(&guid(item_id)).unwrap();
        assert_eq!(selection.composition_id(), item_id);
        assert_eq!(selection.name(), occurrence.item_name);
        assert_eq!(
            selection.dimensions(),
            if item_id == 2165 {
                [1080, 1920]
            } else {
                [2160, 3840]
            }
        );
        let picture = selection
            .import_picture(target(7, next_id), &mut media)
            .unwrap();
        assert_eq!(group(&picture.root).name, occurrence.item_name);
        assert_eq!(picture.root.parent_id(), Some(LayerId::new(7)));
        let mut ids = Vec::new();
        numeric_ids(picture.root.wire_value(), &mut ids);
        assert!(ids.iter().all(|id| (next_id..picture.next_id).contains(id)));
        assert_eq!(ids.iter().collect::<BTreeSet<_>>().len(), ids.len());
        next_id = picture.next_id;
        let mut content = Vec::new();
        layers(&picture.root, &mut content);
        assert!(
            content
                .iter()
                .all(|layer| !matches!(layer.data(), LayerData::Video(_) | LayerData::Image(_)))
        );
        assert!(
            picture
                .animations
                .iter()
                .all(|entry| !entry.animator.is_js_script())
        );
        if item_id == 121 {
            let text: Vec<_> = content
                .iter()
                .filter_map(|layer| match layer.data() {
                    LayerData::Text(text) => Some((
                        text.source_text.text.as_str(),
                        text.source_text.font_size.value(),
                    )),
                    _ => None,
                })
                .collect();
            assert_eq!(text, [("RESULTS", 182.0), ("FINAL", 148.0)]);
        } else {
            // Native Soli dimensions/colors distinguish retained content from an
            // empty identity envelope or a generic nonempty replacement.
            let (size, color) = match item_id {
                1 => ([2160.0, 3840.0], [0.0, 0.0, 0.0, 1.0]),
                41 => ([2160.0, 2160.0], [0.0, 0.0, 0.0, 1.0]),
                92 => (
                    [2160.0, 2160.0],
                    [0.787301_f32, 0.140612, 0.140612, 1.0].map(f64::from),
                ),
                2165 => ([1080.0, 1920.0], [0.0, 0.0, 0.0, 1.0]),
                _ => panic!("unexpected native target {item_id}"),
            };
            assert!(content.iter().any(|layer| match layer.data() {
                LayerData::Rect(rect) => {
                    rect.rect.size == size
                        && rect.rect.fill_color == color
                        && rect.rect.fill_enabled
                }
                _ => false,
            }));
        }
        if item_id == 41 {
            let inspection = selection.inspect_media(None).unwrap();
            let native_video = inspection
                .media
                .iter()
                .find(|source| source.id == "53")
                .unwrap();
            assert_eq!(native_video.kind, fx_conv::MediaKind::Video);
            assert_eq!(native_video.status, fx_conv::MediaStatus::Missing);
            assert_eq!(native_video.name, "C20250915_0989.MP4");
            assert!(
                native_video
                    .references
                    .iter()
                    .any(|reference| { reference == "composition 41 layer 54" })
            );
        }
        for (composition_id, layer_id, basename) in [
            (1, 14, "C0459.MP4"),
            (41, 54, "C20250915_0989.MP4"),
            (121, 134, "title bg.psd"),
        ] {
            if item_id != composition_id {
                continue;
            }
            assert!(picture.diagnostics.iter().any(|note| {
                note.limitation == Limitation::Placeholder
                    && note.composition_id == Some(composition_id)
                    && note.layer_id == Some(layer_id)
                    && note.message.contains(basename)
                    && note
                        .message
                        .contains("no FX reference or animation emitted")
            }));
            assert!(picture.diagnostics.iter().any(|note| {
                note.limitation == Limitation::Placeholder
                    && note.message.contains(basename)
                    && note.message.contains("local source is missing")
            }));
        }
    }
    // Missing footage was not replaced by a raster, slate or synthetic media asset.
    assert!(media.assets.is_empty());
    media.verify_sources().unwrap();
    assert_eq!(fs::read(input).unwrap(), FORMAT96);
}

#[test]
fn native_format96_profile_neighbors_and_unproven_guids_are_rejected() {
    let root = tempfile::tempdir().unwrap();
    let input = root.path().join("input.aep");
    let at = FORMAT96
        .windows(8)
        .position(|v| v == b"head\0\0\0\x14")
        .unwrap()
        + 8;
    assert_eq!(
        &FORMAT96[at..at + 8],
        &[0, 96, 0, 6, 0x0f, 0x8a, 0x06, 0x56]
    );
    for offset in 0..8 {
        let mut changed = FORMAT96.to_vec();
        changed[at + offset] ^= 1;
        fs::write(&input, changed).unwrap();
        assert!(matches!(
            AfterEffects.prepare_linked_import(&input),
            Err(DynamicLinkImportError::UnsupportedProfile { .. })
        ));
    }
    fs::write(&input, FORMAT96).unwrap();
    let prepared = AfterEffects.prepare_linked_import(&input).unwrap();
    let mut suffix = guid(121);
    suffix[15] = 1;
    for unsupported in [guid(0), suffix] {
        assert!(matches!(
            prepared.resolve_composition(&unsupported),
            Err(DynamicLinkImportError::UnsupportedGuid)
        ));
    }
    for absent_or_footage in [66, 13] {
        assert!(matches!(
            prepared.resolve_composition(&guid(absent_or_footage)),
            Err(DynamicLinkImportError::MissingComposition(id)) if id == absent_or_footage
        ));
    }
}
