//! The measured Film Impact default dissolve profile, not a general Ease mapping.
use super::film_impact::{self, read_profile_with, ProfileParam};
use crate::{
    error::Result,
    format::{Graph, Record},
};

// Native Film Impact component 1610, all 27 profiles identical. Record identities
// are deliberately absent: only semantic controls select this profile.
const PROFILE: [ProfileParam; 30] = [
    film_impact::ERROR_OCCURRED,
    film_impact::TRANSITION_TIMING_8120,
    film_impact::START,
    film_impact::END,
    film_impact::TRANSITION_TIMING_8121,
    ProfileParam {
        id: "19",
        kind: "VideoComponentParam",
        name: Some("Controls"),
        control: Some("11"),
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: Some("false"),
        discontinuous: None,
    },
    film_impact::CONTROL_8040,
    ProfileParam {
        id: "22",
        kind: "VideoComponentParam",
        name: Some("Seed"),
        control: None,
        start: Some("-91445760000000000,0.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("99999"),
        discontinuous: None,
    },
    film_impact::VISUAL_CURVE_EDITOR_8020,
    film_impact::CURVE_GRAPH,
    ProfileParam {
        id: "16",
        kind: "VideoComponentParam",
        name: Some("Ease In"),
        control: None,
        start: Some("-91445760000000000,34.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    ProfileParam {
        id: "17",
        kind: "VideoComponentParam",
        name: Some("Ease Out"),
        control: None,
        start: Some("-91445760000000000,34.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    film_impact::VISUAL_CURVE_EDITOR_8021,
    ProfileParam {
        id: "5",
        kind: "VideoComponentParam",
        name: Some("Type"),
        control: None,
        start: Some("-91445760000000000,0,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("4"),
        discontinuous: Some("true"),
    },
    ProfileParam {
        id: "34",
        kind: "VideoComponentParam",
        name: Some("Type"),
        control: None,
        start: Some("-91445760000000000,0,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("3"),
        discontinuous: Some("true"),
    },
    ProfileParam {
        id: "31",
        kind: "VideoComponentParam",
        name: Some("Focus Amount"),
        control: None,
        start: Some("-91445760000000000,0.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    ProfileParam {
        id: "32",
        kind: "PointComponentParam",
        name: Some("Focus Position"),
        control: None,
        start: Some("-91445760000000000,0.5:0.5,0,0,0,0,0,0,5,4,0,0,0,0"),
        lower: None,
        upper: None,
        discontinuous: None,
    },
    ProfileParam {
        id: "33",
        kind: "VideoComponentParam",
        name: Some("Invert Focus"),
        control: None,
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: None,
        discontinuous: None,
    },
    ProfileParam {
        id: "20",
        kind: "VideoComponentParam",
        name: Some("Controls"),
        control: Some("12"),
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: Some("false"),
        discontinuous: None,
    },
    film_impact::OVERLAY_MODE,
    film_impact::OVERLAY_INFO,
    film_impact::CONTROL_8141,
    ProfileParam {
        id: "24",
        kind: "VideoComponentParam",
        name: Some("_ Applied Version"),
        control: None,
        start: Some("-91445760000000000,260300.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("999999"),
        discontinuous: None,
    },
    film_impact::CONTROL_8300,
    film_impact::CONTROL_8301,
    film_impact::SOURCE_B_LAYER,
    film_impact::OVERLAY_ENABLED,
    film_impact::SEQUENCE_WIDTH,
    film_impact::SEQUENCE_HEIGHT,
    film_impact::SEQUENCE_PIXEL_RATIO,
];

pub(super) fn read_profile(graph: &Graph<'_>, record: Record<'_>) -> Result<()> {
    read_profile_with(graph, record, "AE.AE_Impact_Dissolve", &PROFILE)
}
