//! Exact measured Pop profile; render parameters select a bounded geometry approximation.
use super::film_impact::{self, read_profile_with, ProfileParam};
use crate::{
    error::Result,
    format::{Graph, Record},
};

// Native Film Impact component 1607. Identity and duration are not profile controls.
const PROFILE: [ProfileParam; 43] = [
    film_impact::ERROR_OCCURRED,
    film_impact::TRANSITION_TIMING_8120,
    film_impact::START,
    film_impact::END,
    film_impact::TRANSITION_TIMING_8121,
    ProfileParam {
        id: "5",
        kind: "VideoComponentParam",
        name: Some("Presets"),
        control: None,
        start: Some("-91445760000000000,0,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("7"),
        discontinuous: Some("true"),
    },
    ProfileParam {
        id: "38",
        kind: "VideoComponentParam",
        name: Some("Controls"),
        control: Some("11"),
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: Some("false"),
        discontinuous: None,
    },
    film_impact::CONTROL_8040,
    ProfileParam {
        id: "45",
        kind: "VideoComponentParam",
        name: Some("Seed"),
        control: None,
        start: Some("-91445760000000000,0.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("99999"),
        discontinuous: None,
    },
    film_impact::VISUAL_CURVE_EDITOR_8020,
    film_impact::CURVE_GRAPH,
    ProfileParam {
        id: "8",
        kind: "VideoComponentParam",
        name: Some("Type"),
        control: None,
        start: Some("-91445760000000000,1,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("2"),
        discontinuous: Some("true"),
    },
    ProfileParam {
        id: "9",
        kind: "VideoComponentParam",
        name: Some("Bounces"),
        control: None,
        start: Some("-91445760000000000,3.,0,0,0,0,0,0"),
        lower: Some("1"),
        upper: Some("20"),
        discontinuous: None,
    },
    ProfileParam {
        id: "10",
        kind: "VideoComponentParam",
        name: Some("Initial Velocity"),
        control: None,
        start: Some("-91445760000000000,8.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    ProfileParam {
        id: "11",
        kind: "VideoComponentParam",
        name: Some("Elasticity"),
        control: None,
        start: Some("-91445760000000000,10.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("50"),
        discontinuous: None,
    },
    ProfileParam {
        id: "12",
        kind: "VideoComponentParam",
        name: Some("Frequency"),
        control: None,
        start: Some("-91445760000000000,2.,0,0,0,0,0,0"),
        lower: Some("1"),
        upper: Some("20"),
        discontinuous: None,
    },
    ProfileParam {
        id: "13",
        kind: "VideoComponentParam",
        name: Some("Amplitude"),
        control: None,
        start: Some("-91445760000000000,60.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    ProfileParam {
        id: "14",
        kind: "VideoComponentParam",
        name: Some("Decay"),
        control: None,
        start: Some("-91445760000000000,100.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    ProfileParam {
        id: "37",
        kind: "VideoComponentParam",
        name: Some("Prevent Undershoot"),
        control: None,
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: None,
        discontinuous: None,
    },
    ProfileParam {
        id: "35",
        kind: "VideoComponentParam",
        name: Some("Ease In"),
        control: None,
        start: Some("-91445760000000000,0.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    ProfileParam {
        id: "36",
        kind: "VideoComponentParam",
        name: Some("Ease Out"),
        control: None,
        start: Some("-91445760000000000,70.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    ProfileParam {
        id: "54",
        kind: "VideoComponentParam",
        name: Some("Fade"),
        control: None,
        start: Some("-91445760000000000,25.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    film_impact::VISUAL_CURVE_EDITOR_8021,
    ProfileParam {
        id: "40",
        kind: "VideoComponentParam",
        name: Some("Animation Controls"),
        control: Some("11"),
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: Some("false"),
        discontinuous: None,
    },
    ProfileParam {
        id: "26",
        kind: "PointComponentParam",
        name: Some("Origin"),
        control: None,
        start: Some("-91445760000000000,0:0,0,0,0,0,0,0,5,4,0,0,0,0"),
        lower: None,
        upper: None,
        discontinuous: None,
    },
    ProfileParam {
        id: "41",
        kind: "VideoComponentParam",
        name: Some("Animation Controls"),
        control: Some("12"),
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: Some("false"),
        discontinuous: None,
    },
    ProfileParam {
        id: "42",
        kind: "VideoComponentParam",
        name: Some("Motion Blur Engine"),
        control: Some("11"),
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: Some("false"),
        discontinuous: None,
    },
    ProfileParam {
        id: "19",
        kind: "VideoComponentParam",
        name: Some("Enable Motion Blur"),
        control: None,
        start: Some("-91445760000000000,true,0,0,0,0,0,0"),
        lower: None,
        upper: None,
        discontinuous: None,
    },
    ProfileParam {
        id: "20",
        kind: "VideoComponentParam",
        name: Some("Motion Blur"),
        control: None,
        start: Some("-91445760000000000,45.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("100"),
        discontinuous: None,
    },
    ProfileParam {
        id: "43",
        kind: "VideoComponentParam",
        name: Some("Motion Blur Engine"),
        control: Some("12"),
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: Some("false"),
        discontinuous: None,
    },
    ProfileParam {
        id: "39",
        kind: "VideoComponentParam",
        name: Some("Controls"),
        control: Some("12"),
        start: Some("-91445760000000000,false,0,0,0,0,0,0"),
        lower: None,
        upper: Some("false"),
        discontinuous: None,
    },
    film_impact::OVERLAY_MODE,
    film_impact::OVERLAY_INFO,
    film_impact::CONTROL_8141,
    ProfileParam {
        id: "47",
        kind: "VideoComponentParam",
        name: Some("_ Applied Version"),
        control: None,
        start: Some("-91445760000000000,260300.,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("999999"),
        discontinuous: None,
    },
    ProfileParam {
        id: "27",
        kind: "VideoComponentParam",
        name: Some("_ Old Applied Version"),
        control: Some("1"),
        start: Some("-91445760000000000,99,0,0,0,0,0,0"),
        lower: Some("0"),
        upper: Some("99"),
        discontinuous: None,
    },
    film_impact::CONTROL_8300,
    film_impact::CONTROL_8301,
    film_impact::SOURCE_B_LAYER,
    film_impact::OVERLAY_ENABLED,
    film_impact::SEQUENCE_WIDTH,
    film_impact::SEQUENCE_HEIGHT,
    film_impact::SEQUENCE_PIXEL_RATIO,
];

pub(super) fn read_profile(graph: &Graph<'_>, record: Record<'_>) -> Result<()> {
    read_profile_with(graph, record, "AE.AE_Impact_Pop", &PROFILE)
}
